# Use Ubuntu as base image
FROM python:3.9-slim

ENV TZ=Asia/Jerusalem

RUN apt-get update && apt-get install curl -y \
    net-tools \
    nano \
    curl \
    dnsutils \
    iputils-ping \
    iproute2
    
    RUN pip install --no-cache-dir -r requirements.txt --break-system-packages

CMD ["/src/web_server/init.sh"]
# CMD ["/bin/bash"]
