version: '3.8'

services:
  web_server:
    image: web_server_image
    container_name: web_server
    ports:
      - '80:80'
    build:
      context: .
      dockerfile: Dockerfile_web_server
    environment:
      - DOCKER_CONTAINER_NAME=web_Server
    networks:
      sergei_network:
        aliases:
            - web_server.sergei
        ipv4_address: 192.168.2.7
    volumes:
      - ./src:/src
      - /etc/localtime:/etc/localtime:ro
      - /var/log/sergei:/log
    depends_on:
      - db_server
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"     
  
  waha:
    image: devlikeapro/waha:arm
    container_name: waha
    ports:
      - '3000:3000/tcp'
    networks:
      sergei_network:
        aliases:
          - waha.sergei
        ipv4_address: 192.168.2.9
    environment:
      - WHATSAPP_HOOK_URL=http://192.168.10.2/whatsapp/event
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_START_SESSION=default
      - WHATSAPP_RESTART_ALL_SESSIONS=True
    depends_on:
      - web_server
      - db_server
      - scheduler
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"     
  
  wahaGet:
    image: devlikeapro/waha:arm
    container_name: wahaGet
    ports:
      - '5000:5000/tcp'
    networks:
      sergei_network:
        aliases:
          - wahaget.sergei
        ipv4_address: 192.168.2.10
    environment:
      - WHATSAPP_HOOK_URL=http://192.168.10.2/wahaGet/deleted_messages/get
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_START_SESSION=default
      - WHATSAPP_API_PORT=5000
      - WHATSAPP_RESTART_ALL_SESSIONS=True
    depends_on:
      - web_server
      - db_server
      - scheduler
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"      
        
networks:
  sergei_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
    driver_opts:
      com.docker.network.bridge.name: sergei_network
    name: sergei_network
