version: '3.8'

services:
  handler:
    image: handler_image
    container_name: handler
    ports:
      - '80:80'
    build:
      context: .
      dockerfile: Dockerfile_handler
    environment:
      - DOCKER_CONTAINER_NAME=handler
    networks:
      sergei_network:
        aliases:
            - handler.child_tracker
        ipv4_address: 192.168.2.7
    volumes:
      - ./src:/src
      - /etc/localtime:/etc/localtime:ro
      - /var/log/sergei:/log
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"     
    command: "tail -f"
  mother:
    image: devlikeapro/waha
    container_name: mother
    ports:
      - '3000:3000/tcp'
    networks:
      sergei_network:
        aliases:
          - mother.child_tracker
        ipv4_address: 192.168.2.9
    environment:
      - WHATSAPP_HOOK_URL=http://localhost/whatsapp/event
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_START_SESSION=default
      - WHATSAPP_RESTART_ALL_SESSIONS=True
    depends_on:
      - handler
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"     
  
  child:
    image: devlikeapro/waha
    container_name: child
    ports:
      - '5000:5000/tcp'
    networks:
      sergei_network:
        aliases:
          - child.child_tracker
        ipv4_address: 192.168.2.10
    environment:
      - WHATSAPP_HOOK_URL=http://localhost/child/save_new_message
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_START_SESSION=default
      - WHATSAPP_API_PORT=5000
      - WHATSAPP_RESTART_ALL_SESSIONS=True
    depends_on:
      - handler
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   
        max-file: "2"      
        
networks:
  sergei_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
    driver_opts:
      com.docker.network.bridge.name: sergei_network
    name: sergei_network
