# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    net-tools \
    nano \
    dnsutils \
    iputils-ping \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /src

# Copy requirements.txt into the image
RUN pip install --upgrade pip
# Install Python dependencies
RUN pip install -r /src/requirements.txt --break-system-packages

# Copy the application code
COPY src/ /src
