
import requests
from pprint import pprint
from whatsapp.whatsapp_api import users
group_exm = {'event': 'message', 'session': 'default', 'me': {'id': '972524561028@c.us', 'pushName': 'Disc'}, 'payload': {'id': 'false_120363311022400580@g.us_FB7CB6955BD95198E1_972549747174@c.us', 'timestamp': 1718601009, 'from': '120363311022400580@g.us', 'fromMe': False, 'to': '972524561028@c.us', 'body': '*********************************************************', 'hasMedia': False, 'ack': 1, 'ackName': 'SERVER', 'vCards': [], '_data': {'id': {'fromMe': False, 'remote': '120363311022400580@g.us', 'id': 'FB7CB6955BD95198E1', 'participant': '972549747174@c.us', '_serialized': 'false_120363311022400580@g.us_FB7CB6955BD95198E1_972549747174@c.us'}, 'viewed': False, 'body': '*********************************************************', 'type': 'chat', 't': 1718601009, 'notifyName': 'Adi Amilany', 'from': '120363311022400580@g.us', 'to': '972524561028@c.us', 'author': '972549747174@c.us', 'ack': 1, 'invis': False, 'isNewMsg': True, 'star': False, 'kicNotified': False, 'recvFresh': True, 'isFromTemplate': False, 'thumbnail': '', 'pollInvalidated': False, 'isSentCagPollCreation': False, 'latestEditMsgKey': None, 'latestEditSenderTimestampMs': None, 'mentionedJidList': [], 'groupMentions': [], 'isEventCanceled': False, 'eventInvalidated': False, 'isVcardOverMmsDocument': False, 'hasReaction': False, 'ephemeralDuration': 0, 'productHeaderImageRejected': False, 'lastPlaybackProgress': 0, 'isDynamicReplyButtonsMsg': False, 'isCarouselCard': False, 'parentMsgId': None, 'isMdHistoryMsg': False, 'stickerSentTs': 0, 'isAvatar': False, 'lastUpdateFromServerTs': 0, 'invokedBotWid': None, 'bizBotType': None, 'botResponseTargetId': None, 'botPluginType': None, 'botPluginReferenceIndex': None, 'botPluginSearchProvider': None, 'botPluginSearchUrl': None, 'botPluginMaybeParent': False, 'botReelPluginThumbnailCdnUrl': None, 'botMsgBodyType': None, 'requiresDirectConnection': None, 'bizContentPlaceholderType': None, 'hostedBizEncStateMismatch': False, 'senderOrRecipientAccountTypeHosted': False, 'placeholderCreatedWhenAccountIsHosted': False, 'links': []}}, 'engine': 'WEBJS', 'environment': {'version': '2024.6.2', 'engine': 'WEBJS', 'tier': 'CORE', 'browser': '/usr/bin/chromium'}}
dicting = {'engine': 'WEBJS',
 'environment': {'browser': '/usr/bin/chromium',
                 'engine': 'WEBJS',
                 'tier': 'CORE',
                 'version': '2024.6.2'},
 'event': 'message',
 'me': {'id': '972524561028@c.us', 'pushName': 'Disc'},
 'payload': {'_data': {'ack': 1,
                       'bizBotType': None,
                       'bizContentPlaceholderType': None,
                       'body': 'היי היי',
                       'botMsgBodyType': None,
                       'botPluginMaybeParent': False,
                       'botPluginReferenceIndex': None,
                       'botPluginSearchProvider': None,
                       'botPluginSearchUrl': None,
                       'botPluginType': None,
                       'botReelPluginThumbnailCdnUrl': None,
                       'botResponseTargetId': None,
                       'disappearingModeInitiator': 'chat',
                       'disappearingModeTrigger': 'chat_settings',
                       'ephemeralDuration': 0,
                       'ephemeralSettingTimestamp': 0,
                       'eventInvalidated': False,
                       'from': '972549747174@c.us',
                       'groupMentions': [],
                       'hasReaction': False,
                       'hostedBizEncStateMismatch': False,
                       'id': {'_serialized': 'false_972549747174@c.us_0007A0DF5A599E8113',
                              'fromMe': False,
                              'id': '0007A0DF5A599E8113',
                              'remote': '972549747174@c.us'},
                       'invis': False,
                       'invokedBotWid': None,
                       'isAvatar': False,
                       'isCarouselCard': False,
                       'isDynamicReplyButtonsMsg': False,
                       'isEventCanceled': False,
                       'isFromTemplate': False,
                       'isMdHistoryMsg': False,
                       'isNewMsg': True,
                       'isSentCagPollCreation': False,
                       'isVcardOverMmsDocument': False,
                       'kicNotified': False,
                       'lastPlaybackProgress': 0,
                       'lastUpdateFromServerTs': 0,
                       'latestEditMsgKey': None,
                       'latestEditSenderTimestampMs': None,
                       'links': [],
                       'mentionedJidList': [],
                       'notifyName': 'Adi Amilany',
                       'parentMsgId': None,
                       'placeholderCreatedWhenAccountIsHosted': False,
                       'pollInvalidated': False,
                       'productHeaderImageRejected': False,
                       'recvFresh': True,
                       'requiresDirectConnection': None,
                       'senderOrRecipientAccountTypeHosted': False,
                       'star': False,
                       'stickerSentTs': 0,
                       't': 1718096805,
                       'thumbnail': '',
                       'to': '972524561028@c.us',
                       'type': 'chat',
                       'viewed': False},
             'ack': 1,
             'ackName': 'SERVER',
             'body': 'היי היי',
             'from': '972549747174@c.us',
             'fromMe': False,
             'hasMedia': False,
             'id': 'false_972549747174@c.us_0007A0DF5A599E8113',
             'timestamp': 1718096805,
             'to': '972524561028@c.us',
             'vCards': []},
 'session': 'default'}

pprint(group_exm)

{'event': 'message', 'session': 'default', 'me': {'id': '972524561028@c.us', 'pushName': 'Disc'}, 'payload': {'id': 'false_972549747174@c.us_94E1231704A6309149AF0B00113C98FE', 'timestamp': 1719118922, 'from': '972549747174@c.us', 'fromMe': False, 'to': '972524561028@c.us', 'body': 'היי היי', 'hasMedia': False, 'ack': 1, 'ackName': 'SERVER', 'vCards': [], '_data': {'id': {'fromMe': False, 'remote': '972549747174@c.us', 'id': '94E1231704A6309149AF0B00113C98FE', '_serialized': 'false_972549747174@c.us_94E1231704A6309149AF0B00113C98FE'}, 'viewed': False, 'body': 'היי היי', 'type': 'chat', 't': 1719118922, 'notifyName': 'Adi Amilany', 'from': '972549747174@c.us', 'to': '972524561028@c.us', 'ack': 1, 'invis': False, 'isNewMsg': True, 'star': False, 'kicNotified': False, 'recvFresh': True, 'isFromTemplate': False, 'pollInvalidated': False, 'isSentCagPollCreation': False, 'latestEditMsgKey': None, 'latestEditSenderTimestampMs': None, 'mentionedJidList': [], 'groupMentions': [], 'isEventCanceled': False, 'eventInvalidated': False, 'isVcardOverMmsDocument': False, 'isForwarded': False, 'hasReaction': False, 'productHeaderImageRejected': False, 'lastPlaybackProgress': 0, 'isDynamicReplyButtonsMsg': False, 'isCarouselCard': False, 'parentMsgId': None, 'isMdHistoryMsg': False, 'stickerSentTs': 0, 'isAvatar': False, 'lastUpdateFromServerTs': 0, 'invokedBotWid': None, 'bizBotType': None, 'botResponseTargetId': None, 'botPluginType': None, 'botPluginReferenceIndex': None, 'botPluginSearchProvider': None, 'botPluginSearchUrl': None, 'botPluginMaybeParent': False, 'botReelPluginThumbnailCdnUrl': None, 'botMsgBodyType': None, 'requiresDirectConnection': None, 'bizContentPlaceholderType': None, 'hostedBizEncStateMismatch': False, 'senderOrRecipientAccountTypeHosted': False, 'placeholderCreatedWhenAccountIsHosted': False, 'links': []}}, 'engine': 'WEBJS', 'environment': {'version': '2024.6.2', 'engine': 'WEBJS', 'tier': 'CORE', 'browser': '/usr/bin/chromium'}}
{'event': 'message', 'session': 'default', 'me': {'id': '972524561028@c.us', 'pushName': 'Disc'}, 'payload': {'id': 'false_972549747174@c.us_995165191A769AE307', 'timestamp': 1719118909, 'from': '972549747174@c.us', 'fromMe': False, 'to': '972524561028@c.us', 'body': 'היי הייי', 'hasMedia': False, 'ack': 1, 'ackName': 'SERVER', 'vCards': [], '_data': {'id': {'fromMe': False, 'remote': '972549747174@c.us', 'id': '995165191A769AE307', '_serialized': 'false_972549747174@c.us_995165191A769AE307'}, 'viewed': False, 'body': 'היי הייי', 'type': 'chat', 't': 1719118909, 'notifyName': 'Adi Amilany', 'from': '972549747174@c.us', 'to': '972524561028@c.us', 'ack': 1, 'invis': False, 'isNewMsg': True, 'star': False, 'kicNotified': False, 'recvFresh': True, 'isFromTemplate': False, 'thumbnail': '', 'pollInvalidated': False, 'isSentCagPollCreation': False, 'latestEditMsgKey': None, 'latestEditSenderTimestampMs': None, 'mentionedJidList': [], 'groupMentions': [], 'isEventCanceled': False, 'eventInvalidated': False, 'isVcardOverMmsDocument': False, 'hasReaction': False, 'ephemeralDuration': 0, 'ephemeralSettingTimestamp': 0, 'disappearingModeInitiator': 'chat', 'disappearingModeTrigger': 'chat_settings', 'productHeaderImageRejected': False, 'lastPlaybackProgress': 0, 'isDynamicReplyButtonsMsg': False, 'isCarouselCard': False, 'parentMsgId': None, 'isMdHistoryMsg': False, 'stickerSentTs': 0, 'isAvatar': False, 'lastUpdateFromServerTs': 0, 'invokedBotWid': None, 'bizBotType': None, 'botResponseTargetId': None, 'botPluginType': None, 'botPluginReferenceIndex': None, 'botPluginSearchProvider': None, 'botPluginSearchUrl': None, 'botPluginMaybeParent': False, 'botReelPluginThumbnailCdnUrl': None, 'botMsgBodyType': None, 'requiresDirectConnection': None, 'bizContentPlaceholderType': None, 'hostedBizEncStateMismatch': False, 'senderOrRecipientAccountTypeHosted': False, 'placeholderCreatedWhenAccountIsHosted': False, 'links': []}}, 'engine': 'WEBJS', 'environment': {'version': '2024.6.2', 'engine': 'WEBJS', 'tier': 'CORE', 'browser': '/usr/bin/chromium'}}